version: "3.9"

services:
  api:
    build: .
    container_name: student-life-toolkit-api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_URL=mongodb://mongo:27017/student-life-toolkit
      - JWT_SECRET=your_secret_key
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: student-life-toolkit-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
